apiVersion: apps/v1
kind: Deployment
metadata:
        name: d1l1th1um-deployment
spec:
        replicas: 2
        strategy:
                type: RollingUpdate
                rollingUpdate:
                        maxSurge: 25%
                        maxUnavailable: 25%
                
        selector:
                matchLabels:
                        app: d1l1th1um
        template:
                metadata:
                        labels:
                                app: d1l1th1um
                spec:
                        containers:
                        - name: nginx
                          image: nginx:latest
                          ports:
                          - containerPort: 80
