apiVersion: v1
kind: Service
metadata:
        name: d1l1th1um-loadbalancer
        annotations:
                loadbalancer.openstack.org/class: "cmc-loadbalancer-public"
spec:
        selector:
                app: d1l1th1um
        ports:
        - protocol: TCP
          port: 80
          targetPort: 80 
        type: LoadBalancer 
