apiVersion: v1
kind: Pod
metadata:
    name: d1l1th1um-nginx
    labels:
        app: d1l1th1um 
spec:
    containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80 
